permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 刘少星
  email: liu_shaoxing@163.com
  link: http://github.com/liushaoxing321
  github: http://github.com/liushaoxing321

# 站点信息
title: 刘少星的博客 
description: 刘少星的博客
url: http://liushaoxing321.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/931743010/931743010.github.io/master/site-avatar.png
favicon: https://raw.githubusercontent.com/931743010/931743010.github.io/master/site-favicon.ico


# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: hujun-zh
